name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-16"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiY2I3ZGM5MTgtODVmYi00ZmUwLWFmN2UtNDNhNWZkNTU3ODI4IiwidGVuYW50X2lkIjoiNzY3YTUxYTBmNzg0YzdhOTM4MzEzM2RhNjNhYmRhM2U3Y2E4NzZjMjlhNTA1ZTJkODdkMzhhNGUyZTJhMDk1NCIsImludGVybmFsX3NlY3JldCI6IjE3MDdiM2EwLTQyMTMtNDhlMy05NDFhLTFlMjlmZGMyMTRhNyJ9.fL1O_9yaY3ZsQtdTEBxWP6k3gtOGYyk6bEJfj6rr4Rw"
JWT_SECRET = "Kartikey"













